-- Script to initialize (or reset) the database
-- all SCHEMAs, TABLEs and other objects are dropped
-- and SCHEMAs are created

--DROP SCHEMA IF EXISTS "DATAVAULT_CONTROLLING" CASCADE;
--CREATE SCHEMA "DATAVAULT_CONTROLLING";

DROP SCHEMA IF EXISTS "DATAVAULT" CASCADE;
CREATE SCHEMA "DATAVAULT";

DROP SCHEMA IF EXISTS "DATAVAULT_PSA" CASCADE;
CREATE SCHEMA "DATAVAULT_PSA";

DROP SCHEMA IF EXISTS "SALES" CASCADE;
CREATE SCHEMA "SALES";
