CREATE ROLE sales_users;
CREATE ROLE dwh_admins;
CREATE ROLE dwh_users;
--CREATE ROLE controlling_admins;
--CREATE ROLE controlling_users;

GRANT USAGE ON SCHEMA "SALES" TO sales_users;
GRANT USAGE ON SCHEMA "DATAVAULT_PSA" TO dwh_admins;
GRANT USAGE ON SCHEMA "DATAVAULT" TO dwh_admins;
GRANT USAGE ON SCHEMA "DATAVAULT" TO dwh_users;
--GRANT USAGE ON SCHEMA "DATAVAULT_CONTROLLING" TO controlling_admins;
--GRANT USAGE ON SCHEMA "DATAVAULT_CONTROLLING" TO controlling_users;

GRANT dwh_users TO controlling_admins WITH INHERIT TRUE;

--CREATE USER john_doe WITH PASSWORD 'Start123!';

--GRANT sales_users, dwh_admins, controlling_admins TO john_doe WITH INHERIT TRUE;

GRANT SELECT ON ALL TABLES IN SCHEMA "SALES" TO sales_users;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "DATAVAULT_PSA" TO dwh_admins;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "DATAVAULT" TO dwh_admins;
--GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "DATAVAULT_CONTROLLING" TO controlling_admins;

GRANT SELECT ON ALL TABLES IN SCHEMA "DATAVAULT" TO dwh_users;

--GRANT SELECT ON ALL TABLES IN SCHEMA "DATAVAULT_CONTROLLING" TO controlling_users;

