name: dbtvault_Data_Warehouse
profile: dbtvault_Data_Warehouse
version: '5.3.0'
require-dbt-version: ['>=1.0.0', '<2.0.0']
config-version: 2

vars:
  # disable ghost records
  # ghost records are disabled, because the postgres implementation of ghost records in AutomateDV obviously generates wrong HASH_KEYs
  enable_ghost_records: false

analysis-paths:
  - analysis
clean-targets:
  - target
seed-paths:
  - seeds
macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
target-path: target

models:
  +on_schema_change: "fail"
  dbtvault_Data_Warehouse:
    s01_psa_stage:
      +schema: PSA
      tags:
        - 'psa'
      materialized: incremental
      +grants:
          select: ['dwh_admins']
      sales:
        tags:
          - 'psa_sales'
    s02_raw_stage:
      tags:
        - 'raw'
      materialized: view
      +grants:
          select: ['dwh_admins']
      sales:
        tags:
          - 'raw_sales'
    s03_stage:
      tags:
        - 'stage'
      enabled: true
      materialized: table
      +grants:
          select: ['dwh_admins']
    s04_raw_vault:
      tags:
        - 'raw_vault'
      materialized: incremental
      +grants:
          select: ['dwh_admins', 'dwh_users']
      hub:
        tags:
          - 'raw_vault_hub'
      link:
        tags:
          - 'raw_vault_link'
      sat:
        tags:
          - 'raw_vault_sat'
      mas:
        tags:
          - 'raw_vault_mas'
      xts:
        tags:
          - 'raw_vault_xts'
      vlink:
        tags:
          - 'raw_vault_vlink'
        materialized: view
      vsat:
        tags:
          - 'raw_vault_vsat'
        materialized: view
      vmas:
        tags:
          - 'raw_vault_vmas'
        materialized: view
      vxts:
        tags:
          - 'raw_vault_vxts'
        materialized: view
    #s05_bv_raw_stage:
    #  tags:
    #    - 'bv_raw'
    #  materialized: view
    #  +grants:
    #      select: ['dwh_admins']
    #s06_bv_stage:
    #  tags:
    #    - 'bv_stage'
    #  enabled: true
    #  materialized: table
    #  +grants:
    #      select: ['dwh_admins']
    s07_business_vault:
      tags:
        - 'business_vault'
      materialized: incremental
      +grants:
          select: ['dwh_admins', 'dwh_users']
      as_of_date:
        tags:
          - 'as_of_date'
        materialized: table
      pit:
        tags:
          - 'pit'
        materialized: pit_incremental
        +grants:
            select: ['dwh_admins', 'dwh_users']
    # an example for a model directory of a data mart
    #s08_mart_controlling:
    #  +schema: CONTROLLING
    #  tags:
    #    - 'marts'
    #    - 'mart_controlling'
    #  materialized: table
    #  +grants:
    #      select: ['controlling_admins', 'controlling_users']

